### ISSUE TITLE
error: ‘MUMPS_solve’ is not a member of ‘gmm’ [-Wtemplate-body]

### ISSUE THREAD

**Issue by sagitter** [getfem-doc/getfem#65]
Hi all.

Following error occurs by executing tests of `gmm-5.4.4` on Fedora:

```
+ cd gmm-5.4.4
+ make check -k
Making check in include
make[1]: Entering directory '/home/sagitter/rpmbuild/BUILD/gmm-5.4.4-build/gmm-5.4.4/include'
make[1]: Nothing to be done for 'check'.
make[1]: Leaving directory '/home/sagitter/rpmbuild/BUILD/gmm-5.4.4-build/gmm-5.4.4/include'
Making check in tests
make[1]: Entering directory '/home/sagitter/rpmbuild/BUILD/gmm-5.4.4-build/gmm-5.4.4/tests'
make  dummy
make[2]: Entering directory '/home/sagitter/rpmbuild/BUILD/gmm-5.4.4-build/gmm-5.4.4/tests'
g++ -DHAVE_CONFIG_H -I. -I.. -I../include -I../include    -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer  -ftemplate-depth-40 -pedantic -O3 -Wall -W -Wshadow -Wpointer-arith -Wcast-qual -Wwrite-strings -Wconversion -Wredundant-decls -Wno-long-long -c -o dummy.o dummy.cc
/bin/sh ../libtool  --tag=CXX   --mode=link g++  -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer  -ftemplate-depth-40 -pedantic -O3 -Wall -W -Wshadow -Wpointer-arith -Wcast-qual -Wwrite-strings -Wconversion -Wredundant-decls -Wno-long-long  -Wl,-z,relro -Wl,--as-needed   -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -Wl,--build-id=sha1   -o dummy dummy.o -lm  
libtool: link: g++ -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -ftemplate-depth-40 -pedantic -O3 -Wall -W -Wshadow -Wpointer-arith -Wcast-qual -Wwrite-strings -Wconversion -Wredundant-decls -Wno-long-long -Wl,-z -Wl,relro -Wl,--as-needed -Wl,-z -Wl,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -Wl,--build-id=sha1 -o dummy dummy.o  -lm
make[2]: Leaving directory '/home/sagitter/rpmbuild/BUILD/gmm-5.4.4-build/gmm-5.4.4/tests'
make  check-TESTS
make[2]: Entering directory '/home/sagitter/rpmbuild/BUILD/gmm-5.4.4-build/gmm-5.4.4/tests'
make[3]: Entering directory '/home/sagitter/rpmbuild/BUILD/gmm-5.4.4-build/gmm-5.4.4/tests'
FAIL: make_gmm_test.pl
============================================================================
Testsuite summary for gmm 5.4.4
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See tests/test-suite.log
============================================================================
make[3]: *** [Makefile:682: test-suite.log] Error 1
make[3]: Leaving directory '/home/sagitter/rpmbuild/BUILD/gmm-5.4.4-build/gmm-5.4.4/tests'
make[2]: *** [Makefile:790: check-TESTS] Error 2
make[2]: Leaving directory '/home/sagitter/rpmbuild/BUILD/gmm-5.4.4-build/gmm-5.4.4/tests'
make[1]: *** [Makefile:863: check-am] Error 2
make[1]: Target 'check' not remade because of errors.
make[1]: Leaving directory '/home/sagitter/rpmbuild/BUILD/gmm-5.4.4-build/gmm-5.4.4/tests'
make[1]: Entering directory '/home/sagitter/rpmbuild/BUILD/gmm-5.4.4-build/gmm-5.4.4'
make[1]: Leaving directory '/home/sagitter/rpmbuild/BUILD/gmm-5.4.4-build/gmm-5.4.4'
make: *** [Makefile:416: check-recursive] Error 1
make: Target 'check' not remade because of errors.
+ cat tests/test-suite.log
=====================================
   gmm 5.4.4: tests/test-suite.log
=====================================

# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: make_gmm_test.pl
======================

Gmm tests : Making 1 execution of each test
Testing  ./gmm_torture01_lusolve.cc
Testing  ./gmm_torture02_baseop.cc
Testing  ./gmm_torture05_mult.cc
Testing  ./gmm_torture06_mat_mult.cc
Testing  ./gmm_torture10_qr.cc
Testing  ./gmm_torture15_sub.cc
Testing  ./gmm_torture20_iterative_solvers.cc
In file included from ./../include/gmm/gmm_iter_solvers.h:100,
                 from ./../include/gmm/gmm.h:44,
                 from auto_gmm_torture20_iterative_solvers.cc:5:
./../include/gmm/gmm_solver_Schwarz_additive.h: In function ‘void gmm::mult(const AS_exact_gradient<Matrixt, MatrixBi>&, const Vector2&, Vector3&)’:
./../include/gmm/gmm_solver_Schwarz_additive.h:579:12: error: ‘MUMPS_solve’ is not a member of ‘gmm’ [-Wtemplate-body]
  579 |       gmm::MUMPS_solve(M.vMloc[i], x, w);
      |            ^~~~~~~~~~~
g++ -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -ftemplate-depth-40 -pedantic -O3 -Wall -W -Wshadow -Wpointer-arith -Wcast-qual -Wwrite-strings -Wconversion -Wredundant-decls -Wno-long-long -I/usr/include -I./../src -I./../include -I../src -I../include auto_gmm_torture20_iterative_solvers.cc -o auto_gmm_torture20_iterative_solvers -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -Wl,--build-id=sha1 


******************************************************
* Compilation error, please submit this bug to
* Yves.Renard@insa-lyon.fr, with the file
* auto_gmm_torture20_iterative_solvers.cc
* produced in directory "tests".
******************************************************
FAIL make_gmm_test.pl (exit status: 1)
```

**Comment by mohd-akram** [comment]
@yvesrenard @logari81 Has this been fixed? Is there a patch for it?

**Comment by logari81** [comment]
this is a source tarball release issue, we will fix in 5.5

Until then you can still build gmm from getfem tarball

**Comment by mohd-akram** [comment]
@logari81 I am not a user of gmm, but we package it for MacPorts. Does it make sense to wrap `gmm_solver_Schwarz_additive.h` in `#if defined(GMM_USES_SUPERLU) || defined(GMM_USES_MUMPS)` so that other parts of the library are usable if those are not defined?

**Comment by logari81** [comment]
these are the options in gmm_arch_config.h, if this file was generated properly

```
/* src/gmm/gmm_arch_config.h.  Generated from gmm_arch_config.h.in by configure.  */
/* manually created gmm_arch_config.h.in template to be used by autotools.  */

/* gcc style __PRETTY_FUNCTION__ macro */
#define GMM_HAVE_PRETTY_FUNCTION /**/

/* defined if GMM is linked to a blas library */
#define GMM_USES_BLAS /**/

/* defined if GMM is linked to a lapack library */
#define GMM_USES_LAPACK /**/

/* defined if GMM is used when building the Matlab interface */
#define GMM_MATLAB_INTERFACE /**/

/* defined if GMM uses MPI */
/* #undef GMM_USES_MPI */

/* defined if GMM is linked to the mumps library */
#define GMM_USES_MUMPS /**/

/* defined if GMM is linked to the superlu library */
#define GMM_USES_SUPERLU /**/

/* defined if superlu header files are not under a subdirectory called "superlu" */
/* #undef GMM_NO_SUPERLU_INCLUDE_SUBDIR */

/* Use blas with 64 bits integers */
/* #undef GMM_USE_BLAS64_INTERFACE */

/* defined if the BLAS fortran ABI does not return complex values directly (e.g. Intel's MKL) */
/* #undef GMM_BLAS_RETURN_COMPLEX_AS_ARGUMENT */

/* GMM version */
#define GMM_VERSION "5.4.4"
```

you can write this file yourself manually with the set of options that the package user would expect.

**Comment by logari81** [comment]
This issue is resolved in the new release 5.5

**Comment by mohd-akram** [comment]
@logari81 I ran the build with 5.5, and despite it not finding either SuperLU or MUMPS, the build still succeeds with this:

```
- SuperLU not found. Not using the SuperLU library for large sparse linear systems.
- Mumps not found. Not using the MUMPS library for large sparse linear systems.
```

However, that causes the same error when including `gmm/gmm.h`:

```
/opt/local/include/gmm/gmm_solver_Schwarz_additive.h:578:12: error: no member named 'MUMPS_solve' in namespace 'gmm'
  578 |       gmm::MUMPS_solve(M.vMloc[i], x, w);
      |            ^~~~~~~~~~~
17 errors generated.
```

```c
$ cat /opt/local/include/gmm/gmm_arch_config.h
/* include/gmm/gmm_arch_config.h.  Generated from gmm_arch_config.h.in by configure.  */
/* manually created gmm_arch_config.h.in template to be used by autotools.  */

/* gcc style __PRETTY_FUNCTION__ macro */
#define GMM_HAVE_PRETTY_FUNCTION /**/

/* defined if GMM is linked to a blas library */
#define GMM_USES_BLAS /**/

/* defined if GMM is linked to a lapack library */
#define GMM_USES_LAPACK /**/

/* defined if GMM is used when building the Matlab interface */
/* #undef GMM_MATLAB_INTERFACE */

/* defined if GMM uses MPI */
/* #undef GMM_USES_MPI */

/* defined if GMM is linked to the mumps library */
/* #undef GMM_USES_MUMPS */

/* defined if GMM is linked to the superlu library */
/* #undef GMM_USES_SUPERLU */

/* defined if superlu header files are not under a subdirectory called "superlu" */
/* #undef GMM_NO_SUPERLU_INCLUDE_SUBDIR */

/* Use blas with 64 bits integers */
/* #undef GMM_USE_BLAS64_INTERFACE */

/* defined if the BLAS fortran ABI does not return complex values directly (e.g. Intel's MKL) */
#define GMM_BLAS_RETURN_COMPLEX_AS_ARGUMENT /**/

/* GMM version */
#define GMM_VERSION "5.5"
```

If both libraries are optional, would it make sense to `ifdef` both cases as I had mentioned?

**Comment by logari81** [comment]
Ok, I looked into this again. In the current state of gmm, both libraries are not optional, the configure.ac should actually fail if neither superlu nor mumps is present. It is a mistake that it succeeds.

Maybe it is possible to make the linear solvers optional by editing

```
#if defined(GMM_USES_SUPERLU)
      double rcond;
      gmm::SuperLU_solve(M.vMloc[i], x, w, rcond);
#else
      gmm::MUMPS_solve(M.vMloc[i], x, w);
#endif
      // gmm::iteration iter(1E-10, 0, 100000);
      //gmm::gmres(M.vMloc[i], x, w, gmm::identity_matrix(), 50, iter);
```

as

```
#if defined(GMM_USES_SUPERLU)
      double rcond;
      gmm::SuperLU_solve(M.vMloc[i], x, w, rcond);
#elif defined(GMM_USES_MUMPS)
      gmm::MUMPS_solve(M.vMloc[i], x, w);
#else
      gmm::iteration iter(1E-10, 0, 100000);
     gmm::gmres(M.vMloc[i], x, w, gmm::identity_matrix(), 50, iter);
#endif
```

but this needs to be tested. In the current state, at least one linear solver should be required.
